python: 3.6
node_js: 10
  
jobs:
  include:
  - stage: Tox Test
    name: "Pytest Tests"
    language: python
    sudo: required
    dist: xenial
    python: 3.6
    install: pip install tox-travis
    script: tox

  - stage: Cypress Test
    name: "Frontend Cypress Tests"
    language: node_js
    node_js: 10
    npm: true
    directories:
    - /.npm
    - /.cache
    - node_modules
    before_install:
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip install Flask
    - sudo pip install flask-cors

    - python3 -V
    - pip3 -V
    install:
    - npm install
    - npm install --save axios
    - sudo pip3 install -r requirements
    - cd src/main/python/client/frontend/src/router
    - npm ci
    before_script:
    - npm run dev &
    - python ../../../../server/rest.py &
    script:
    - cd ..
    - cd ..
    - $(npm bin)/cypress run --spec 'cypress/integration/test_spec.js' 
